version: "3.8"

services:
  customer:
    image: sterling/form_config_api
    build:
      dockerfile: Dockerfile
      context: "."
      target: "dev"
    ports:
      - 5050:5050
    volumes:
      - .:/src
    command: npm run dev
