export const FORM_CONTROL_PROPERTY = [
  {
    name: "Page name",
    description: "With character limit of 50. It defines the name of the page",
    formControlType: "text_input",
    defaultState: "Page [Number]",
    lastModifiedById: "System admin",
    lastModifiedBy: "System admin",
    createdById: "System admin",
    createdBy: "System admin",
  },
  {
    name: "Visibility",
    description: "Toggling on enables page visibility on the form",
    formControlType: "toggle",
    defaultState: "On",
    lastModifiedById: "System admin",
    lastModifiedBy: "System admin",
    createdById: "System admin",
    createdBy: "System admin",
  },
  {
    name: "Allow modification after submission",
    description:
      "Toggling on enables modification of form item after request submission",
    formControlType: "toggle",
    defaultState: "On",
    lastModifiedById: "System admin",
    lastModifiedBy: "System admin",
    createdById: "System admin",
    createdBy: "System admin",
  },
  {
    name: "Section name",
    description:
      "With character limit of 50. It defines the name of the section",
    formControlType: "text_input",
    defaultState: "Section [Number]",
    lastModifiedById: "System admin",
    lastModifiedBy: "System admin",
    createdById: "System admin",
    createdBy: "System admin",
  },
  {
    name: "Toggle help text",
    description:
      "Toggling on displays information icon, which when clicked, displays help text",
    formControlType: "toggle",
    defaultState: "On",
    lastModifiedById: "System admin",
    lastModifiedBy: "System admin",
    createdById: "System admin",
    createdBy: "System admin",
  },
  {
    name: "Help text",
    description:
      "Help text that is displayed when toggle help text is turned on",
    formControlType: "textarea",
    defaultState: "",
    lastModifiedById: "System admin",
    lastModifiedBy: "System admin",
    createdById: "System admin",
    createdBy: "System admin",
  },
  {
    name: "Number of columns",
    description:
      "Ranges from 1 to 3. This defines the number of columns the section can contain",
    formControlType: "dropdown_field",
    defaultState: "",
    formControlPropertyItems: ["1", "2", "3"],
    lastModifiedById: "System admin",
    lastModifiedBy: "System admin",
    createdById: "System admin",
    createdBy: "System admin",
  },
  {
    name: "Label",
    description: "With character limit of 100. It defines the header text",
    formControlType: "text_input",
    defaultState: "",
    lastModifiedById: "System admin",
    lastModifiedBy: "System admin",
    createdById: "System admin",
    createdBy: "System admin",
  },
  {
    name: "Field label",
    description:
      "With character limit of 100. It defines the short text field label",
    formControlType: "text_input",
    defaultState: "",
    lastModifiedById: "System admin",
    lastModifiedBy: "System admin",
    createdById: "System admin",
    createdBy: "System admin",
  },
  {
    name: "Placeholder",
    description:
      "With character limit of 100. It defines the short text field sub-label",
    formControlType: "text_input",
    defaultState: "",
    lastModifiedById: "System admin",
    lastModifiedBy: "System admin",
    createdById: "System admin",
    createdBy: "System admin",
  },
  {
    name: "Col Span",
    description:
      "Defines the number of columns the form item should take on the page relative to the number of columns defined for the section",
    formControlType: "dropdown_field",
    defaultState: "1",
    lastModifiedById: "System admin",
    lastModifiedBy: "System admin",
    createdById: "System admin",
    createdBy: "System admin",
  },
  {
    name: "Set as Required",
    description: "Toggling on makes the short text field input mandatory",
    formControlType: "toggle",
    defaultState: "Off",
    lastModifiedById: "System admin",
    lastModifiedBy: "System admin",
    createdById: "System admin",
    createdBy: "System admin",
  },
  {
    name: "Character Type",
    description:
      "Defines what character the system should allow for the short text field. Dropdown options include: -String -Integer -Decimal",
    formControlType: "dropdown_field",
    defaultState: "String",
    formControlPropertyItems: ["String", "Integer", "Decimal"],
    lastModifiedById: "System admin",
    lastModifiedBy: "System admin",
    createdById: "System admin",
    createdBy: "System admin",
  },
  {
    name: "Minimum Number of characters",
    description:
      "Defines the minimum number of characters the system should validate in the field",
    formControlType: "numerical_input",
    defaultState: "0",
    lastModifiedById: "System admin",
    lastModifiedBy: "System admin",
    createdById: "System admin",
    createdBy: "System admin",
  },
  {
    name: "Maximum Number of characters",
    description:
      "Defines the maximum number of characters the system should validate in the field",
    formControlType: "numerical_input",
    defaultState: "",
    lastModifiedById: "System admin",
    lastModifiedBy: "System admin",
    createdById: "System admin",
    createdBy: "System admin",
  },
  {
    name: "Enable External Integration",
    description: "Toggling on enables external integration via an API",
    formControlType: "toggle",
    defaultState: "Off",
    lastModifiedById: "System admin",
    lastModifiedBy: "System admin",
    createdById: "System admin",
    createdBy: "System admin",
  },
  {
    name: "Specify Integration API",
    description:
      "This becomes active when 'Enable External Integration' is toggled on. The options are fetched from the Integrations management module, enabling the user to select applicable integration API",
    formControlType: "dropdown_field",
    defaultState: "",
    lastModifiedById: "System admin",
    lastModifiedBy: "System admin",
    createdById: "System admin",
    createdBy: "System admin",
  },
  {
    name: "Dropdown Options List",
    description:
      "Defines what is displayed when the dropdown option is clicked. The options are: - Manual Input - Import from File - Import from URL - Import from API",
    formControlType: "dropdown_field",
    defaultState: "Manual Input",
    formControlPropertyItems: [
      "Manual Input",
      "Import from File",
      "Import from URL",
      "Import from API",
    ],
    lastModifiedById: "System admin",
    lastModifiedBy: "System admin",
    createdById: "System admin",
    createdBy: "System admin",
  },
  {
    name: "Specify Options List",
    description:
      "This field becomes visible when 'Dropdown Options List' field is set to 'Manual Input'. The user inputs the options manually, line by line.",
    formControlType: "textarea",
    defaultState: "",
    lastModifiedById: "System admin",
    lastModifiedBy: "System admin",
    createdById: "System admin",
    createdBy: "System admin",
  },
  {
    name: "Specify API",
    description:
      "This field becomes visible when 'Dropdown Options List' field is set to 'Import from API'. The options are fetched from the Integrations management module, enabling the user to sspecify applicable API",
    formControlType: "dropdown_field",
    defaultState: "",
    lastModifiedById: "System admin",
    lastModifiedBy: "System admin",
    createdById: "System admin",
    createdBy: "System admin",
  },
  {
    name: "Upload List",
    description:
      "This field becomes visible when 'Dropdown Options List' field is set to 'Import from File'. It accepts files in .xls and .xlsx format, containing the list of options",
    formControlType: "file_upload_zone",
    defaultState: "",
    lastModifiedById: "System admin",
    lastModifiedBy: "System admin",
    createdById: "System admin",
    createdBy: "System admin",
  },
  {
    name: "Specify URL",
    description:
      "This field becomes visible when 'Dropdown Options List' field is set to 'Import from URL'. It accepts files in .xls and .xlsx format, containing the list of option",
    formControlType: "textarea",
    defaultState: "",
    lastModifiedById: "System admin",
    lastModifiedBy: "System admin",
    createdById: "System admin",
    createdBy: "System admin",
  },
  {
    name: "Enable multiple selection of options",
    description:
      "Toggling on allows for multiple selection of options from the returned list of values when the dropdown is clicked.",
    formControlType: "toggle",
    defaultState: "Off",
    lastModifiedById: "System admin",
    lastModifiedBy: "System admin",
    createdById: "System admin",
    createdBy: "System admin",
  },
  {
    name: "Default selection",
    description: "Defines the default option for the dropdown item",
    formControlType: "dropdown_field",
    defaultState: "",
    lastModifiedById: "System admin",
    lastModifiedBy: "System admin",
    createdById: "System admin",
    createdBy: "System admin",
  },
  {
    name: "Options arrangement",
    description:
      "The user specifies whether the options would be arranged horizontally or vertically",
    formControlType: "dropdown_field",
    defaultState: "Horizontal",
    formControlPropertyItems: ["Horizontal", "Vertical"],
    lastModifiedById: "System admin",
    lastModifiedBy: "System admin",
    createdById: "System admin",
    createdBy: "System admin",
  },
  {
    name: "Allowable File Types",
    description:
      "Defines the file formats the system should validate during the file upload process. The list of file types include: jpeg, pdf, png",
    formControlType: "textarea",
    defaultState: "jpeg, pdf, png",
    lastModifiedById: "System admin",
    lastModifiedBy: "System admin",
    createdById: "System admin",
    createdBy: "System admin",
  },
  {
    name: "Maximum Number of Files",
    description:
      "Defines the maximum number of files the system should allow during the file upload process ",
    formControlType: "integer_input",
    defaultState: "1",
    lastModifiedById: "System admin",
    lastModifiedBy: "System admin",
    createdById: "System admin",
    createdBy: "System admin",
  },
  {
    name: "Maximum File Size for Each Upload",
    description:
      "Defines the maximum file size the system should allow for each file upload process",
    formControlType: "hybrid",
    defaultState: "",
    hybridFormControlPropertyItems: [
      {
        formControlType: "decimal_input",
        defaultState: "1",
        formControlPropertyItems: [],
      },
      {
        formControlType: "dropdown_field",
        defaultState: "MB",
        formControlPropertyItems: ["KB", "MB", "GB"],
      },
    ],
    lastModifiedById: "System admin",
    lastModifiedBy: "System admin",
    createdById: "System admin",
    createdBy: "System admin",
  },
  {
    name: "Swap label position",
    description:
      "Toggling on enables the position of the field label to changed with respect to the action toggle position e.g if the label is on the right it will be swapped to the left",
    formControlType: "toggle",
    defaultState: "Off",
    lastModifiedById: "System admin",
    lastModifiedBy: "System admin",
    createdById: "System admin",
    createdBy: "System admin",
  },
  {
    name: "Type",
    description:
      "Defines what type of toggle symbol should be displayed. The list of type options include: checkbox, toggle switch",
    formControlType: "dropdown_field",
    defaultState: "checkbox",
    formControlPropertyItems: ["checkbox", "toggle switch"],
    lastModifiedById: "System admin",
    lastModifiedBy: "System admin",
    createdById: "System admin",
    createdBy: "System admin",
  },
  {
    name: "Allowable start date",
    description:
      "Defines the minimum allowable start date to be selected or inputted as a date",
    formControlType: "date_input",
    defaultState: "",
    lastModifiedById: "System admin",
    lastModifiedBy: "System admin",
    createdById: "System admin",
    createdBy: "System admin",
  },
  {
    name: "Allowable end date",
    description:
      "Defines the maximum allowable start date to be selected or inputted as a date",
    formControlType: "date_input",
    defaultState: "",
    lastModifiedById: "System admin",
    lastModifiedBy: "System admin",
    createdById: "System admin",
    createdBy: "System admin",
  },
  {
    name: "Button Type",
    description:
      "Defines the type of button. A dropdown list of button types is shown when clicked: Submit, Reset, Next Page, Previous page, Custom",
    formControlType: "dropdown_field",
    defaultState: "Submit",
    formControlPropertyItems: [
      "Submit",
      "Reset",
      "Next Page",
      "Previous Page",
      "Custom",
    ],
    lastModifiedById: "System admin",
    lastModifiedBy: "System admin",
    createdById: "System admin",
    createdBy: "System admin",
  },
  {
    name: "Action",
    description:
      "Defines what happens when the button is clicked. A dropdown list of action is displayed when clicked: Submit to URL",
    formControlType: "hybrid",
    defaultState: "",
    hybridFormControlPropertyItems: [
      {
        formControlType: "dropdown_field",
        defaultState: "",
        formControlPropertyItems: [],
      },
      {
        formControlType: "text_input",
        defaultState: "Submit to URL",
        formControlPropertyItems: [],
      },
    ],
    lastModifiedById: "System admin",
    lastModifiedBy: "System admin",
    createdById: "System admin",
    createdBy: "System admin",
  },
  {
    name: "Minimum numeric input",
    description:
      "Defines the minimum numeric input for the field. It is set to 0 as default.",
    formControlType: "numerical_input",
    defaultState: "0",
    lastModifiedById: "System admin",
    lastModifiedBy: "System admin",
    createdById: "System admin",
    createdBy: "System admin",
  },
  {
    name: "Maximum numeric input",
    description: "Defines the maximum numeric input for the field.",
    formControlType: "numerical_input",
    defaultState: "",
    lastModifiedById: "System admin",
    lastModifiedBy: "System admin",
    createdById: "System admin",
    createdBy: "System admin",
  },
  {
    name: "Country Code Options List",
    description:
      "Defines what is displayed when the dropdown option is clicked. The options are: - Manual Input - Import from File - Import from URL - Import from API",
    formControlType: "dropdown_field",
    defaultState: "Manual Input",
    formControlPropertyItems: [
      "Manual Input",
      "Import from File",
      "Import from URL",
      "Import from API",
    ],
    lastModifiedById: "System admin",
    lastModifiedBy: "System admin",
    createdById: "System admin",
    createdBy: "System admin",
  },
  {
    name: "Options List",
    description:
      "Defines what is displayed when the dropdown option is clicked. The options are: - Manual Input - Import from File - Import from URL - Import from API",
    formControlType: "dropdown_field",
    defaultState: "Manual Input",
    formControlPropertyItems: [
      "Manual Input",
      "Import from File",
      "Import from URL",
      "Import from API",
    ],
    lastModifiedById: "System admin",
    lastModifiedBy: "System admin",
    createdById: "System admin",
    createdBy: "System admin",
  },
  {
    name: "Lowerbound (Min)",
    description:
      "Defines the minimum allowable time to be selected or inputted as a time",
    formControlType: "time_input",
    defaultState: "",
    lastModifiedById: "System admin",
    lastModifiedBy: "System admin",
    createdById: "System admin",
    createdBy: "System admin",
  },
  {
    name: "Upperbound (Max)",
    description:
      "Defines the maximum allowable time to be selected or inputted as a time",
    formControlType: "time_input",
    defaultState: "",
    lastModifiedById: "System admin",
    lastModifiedBy: "System admin",
    createdById: "System admin",
    createdBy: "System admin",
  },
  {
    name: "Step size",
    description: "Specifies the granularity of the range",
    formControlType: "numerical_input",
    defaultState: "",
    lastModifiedById: "System admin",
    lastModifiedBy: "System admin",
    createdById: "System admin",
    createdBy: "System admin",
  },
  {
    name: "Time format",
    description:
      "Defines the time format for the input field. A dropdown with the following options: 'HH:MM:SS', 'HH:MM', '24 HR', 12 HR (AM or PM options)",
    formControlType: "text_input",
    defaultState: "HH:MM:SS",
    lastModifiedById: "System admin",
    lastModifiedBy: "System admin",
    createdById: "System admin",
    createdBy: "System admin",
  },
];
